name: Validate Build and Tests

on:
  push:
    branches:
      - master
      - develop
      - feature/**
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint check (optional)
        run: npm run lint # nur falls du linting hast

      - name: Build check
        run: npm run build

      - name: Run tests (optional)
        run: npm run test # nur falls du Tests hast
